name: Terraform Format, Init, Validate, Plan

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform Format, Init, Validate, Plan
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false \
            -var="client_id=${ARM_CLIENT_ID}" \
            -var="client_secret=${ARM_CLIENT_SECRET}" \
            -var="tenant_id=${ARM_TENANT_ID}" \
            -var="subscription_id=${ARM_SUBSCRIPTION_ID}" \
            -var="location=eastus" \
            -var="resource_group_name=demo-rg1" \
            -var="vnet_name=demo-vnet" \
            -var='vnet_address_space=["10.0.0.0/16"]'
